name: Sultan Of Search
favicon: null
layout_spectrum: 1
typography_spectrum: 0.72871
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f2f3'
    - '#644e37'
    - '#2d2822'
    - '#9e9da3'
    - '#a0212a'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
